version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: tiknol_postgres
    restart: always
    environment:
      POSTGRES_USER: macbooksale
      POSTGRES_PASSWORD: macbooksale
      POSTGRES_DB: tiknol_reserve_local
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
